apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://__NS_PREFIX__-prometheus-grafana.__NS_PREFIX__-observability.svc.cluster.local
    adminPassword:
      name: grafana-admin-credentials
      key: username
    adminUser:
      name: grafana-admin-credentials
      key: password